// Class automatically generated by Dev-C++ New Class wizard

#include "blip.h" // class's header file

// class constructor
Blip::Blip()
{
	// insert your code here
}

// sets location
Blip::setLoc(Location targetLoc)
{
    loc = targetLoc;
}

// returns Location
Blip::getLoc()
{
    return loc;
}

// class destructor
Blip::~Blip()
{
	// insert your code here
}
