// Class automatically generated by Dev-C++ New Class wizard

#ifndef BLIP_H
#define BLIP_H

/*
 * No description
 */
class Blip
{
	public:
		// class constructor
		Blip();
		// class destructor
		~Blip();
};

#endif // BLIP_H
