// Class automatically generated by Dev-C++ New Class wizard

#include "blip.h" // class's header file

// class constructor
Blip::Blip()
{
	// insert your code here
}

// class destructor
Blip::~Blip()
{
	// insert your code here
}
