// Class automatically generated by Dev-C++ New Class wizard

#ifndef GRID_H
#define GRID_H

/*
 * No description
 */
class Grid
{
	public:
		// class constructor
		Grid(int length, int width);
		// class destructor
		~Grid();
};

#endif // GRID_H
