// Class automatically generated by Dev-C++ New Class wizard

#include "grid.h" // class's header file

// class constructor
Grid::Grid(int width, int height)
{
	for (int i=1;i<=height;i++)
	{
	    for (int j=1;j<=width;j++)
	    {
//	        grid[i][j] = null;
        }
    }
}

// class destructor
Grid::~Grid()
{
	// insert your code here
}
