// Class automatically generated by Dev-C++ New Class wizard

#include "grid.h" // class's header file

// class constructor
Grid::Grid(int length, int width)
{
	// insert your code here
}

// class destructor
Grid::~Grid()
{
	// insert your code here
}
