// Class automatically generated by Dev-C++ New Class wizard

#include "location.h" // class's header file

// class constructor
Location::Location(int startx,int starty)
{
	// x value
	x = startx;
	// y value
	y = starty;
}

// class destructor
Location::~Location()
{
	// insert your code here
}
